# Generated by Django 4.2.1 on 2023-05-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('registro', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso', to_field='codigo')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='NotasAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('avaliacao', models.CharField(max_length=4)),
                ('data', models.DateField()),
                ('codigo_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno', to_field='matricula')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
            options={
                'db_table': 'notasaluno',
            },
        ),
        migrations.CreateModel(
            name='FaltasAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('codigo_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno', to_field='matricula')),
                ('codigo_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.professor', to_field='registro')),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.turma', to_field='codigo')),
            ],
            options={
                'db_table': 'faltasaluno',
            },
        ),
        migrations.CreateModel(
            name='DetalheTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno', to_field='matricula')),
                ('codigo_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.professor', to_field='registro')),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.turma', to_field='codigo')),
            ],
            options={
                'db_table': 'detalhe_turma',
            },
        ),
        migrations.CreateModel(
            name='DetalheDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
                ('codigo_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
            options={
                'db_table': 'detalhedisciplina',
            },
        ),
        migrations.CreateModel(
            name='DetalheCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.turma', to_field='codigo')),
            ],
            options={
                'db_table': 'detalhecurso',
            },
        ),
    ]
