# Generated by Django 4.2.1 on 2023-05-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltasAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('codigo_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno', to_field='matricula', unique=True)),
                ('codigo_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.professor', to_field='registro')),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.turma', to_field='codigo')),
            ],
            options={
                'db_table': 'faltasaluno',
            },
        ),
    ]
